version: '2'

networks:
  app-tier:
    driver: bridge

services:
  tomcat:
    image: 'bitnami/tomcat:latest'
    ports:
      - '8080:8080'
    volumes:
      - /home/bitnami/guides/javak8s/docker/tomcat/sample-app:/bitnami/tomcat/data
    networks:
      - app-tier
  mariadb:
    image: bitnami/mariadb:latest
    environment:
        - MARIADB_USER=jhipster
        - MARIADB_PASSWORD=jhipster
        - MARIADB_DATABASE=jhipsterSampleApplication
        - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
