version: '2.1'

networks:
  app-tier:
    driver: bridge

services:
  tomcat:
    image: 'bitnami/tomcat:latest'
    ports:
      - '8080:8080'
    volumes:
      - /home/bitnami/guides/javak8s/docker/tomcat/sample-app:/bitnami/tomcat/data
    networks:
      - app-tier
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: bitnami/mariadb:latest
    environment:
        - MARIADB_USER=jhipster
        - MARIADB_PASSWORD=jhipster
        - MARIADB_DATABASE=jhipsterSampleApplication
        - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: "/opt/bitnami/mariadb/bin/mysql -u jhipster -pjhipster -e 'SHOW DATABASES;'"
      interval: 30s
      retries: 1
    networks:
      - app-tier
